server:
  port: 3080

spring:
  application:
    name: wechat-messages-server

log:
  path: log

wechat:
  mp:
    appId: xxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxx
    token: xxxxxxxxxxxxxxxxxxxxxxxx
    aesKey: xxxxxxxxxxxxxxxxxxxxxxxx
  msg-push:
    pushInfos:
      - app-id: xxxxxxxxxxxxxxxxxxxxxxxx
        push-url: xxxxxxxxxxxxxxxxxxxxxxxx
        priority: 1
      - app-id: xxxxxxxxxxxxxxxxxxxxxxxx
        push-url: xxxxxxxxxxxxxxxxxxxxxxxx
        priority: 2