server:
  port: 3080

spring:
  application:
    name: wechat-messages-server

log:
  path: log

wechat:
  mp:
    appId: xxxxxxxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxx
    token: xxxxxxxxxxxxxxxxxxxxxxxx
    aesKey: xxxxxxxxxxxxxxxxxxxxxxxx